######################################################################
# Automatically generated by qmake (2.01a) ?? 2? 11 00:52:51 2020
######################################################################

TEMPLATE = lib
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .
ARCHITECTURE = x64
TARGET_ARCH = x86_64
# Input
HEADERS += inenvdirplugin.h inenvdirplugin_global.h
SOURCES += inenvdirplugin.cpp
